var jiggle = 16;
var x1 = random(jiggle);
var x4 = random(jiggle);
var x2 = room_width - random(jiggle);
var x3 = room_width - random(jiggle);
var y1 = random(jiggle);
var y2 = random(jiggle);
var y3 = room_height - random(jiggle);
var y4 = room_height - random(jiggle);

draw_set_color(c_white);
draw_primitive_begin(pr_trianglestrip);
draw_vertex(0,0);
draw_vertex(x1,y1);
draw_vertex(room_width,0);
draw_vertex(x2,y2);
draw_vertex(room_width,room_height);
draw_vertex(x3,y3);
draw_vertex(0,room_height);
draw_vertex(x4,y4);
draw_vertex(0,0);
draw_vertex(x1,y1);
draw_primitive_end();
